= Cheatsheets

[[ErrorLocation]]
== ErrorLocation

++++
 Data object that holds the location of a graphql query error.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[column]]`column`|`Number (int)`|
+++
@return the column where the error occurred
+++
|[[line]]`line`|`Number (int)`|
+++
@return the line where the error occurred
+++
|===

[[QueryError]]
== QueryError

++++
 Data object that represents an error that occurred upon execution of a GraphQL query.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[errorType]]`errorType`|`String`|
+++
Gets the type of the graphql execution error.
 <p>
 The possible types are determined by the `ValidationErrorType` enum defined in the GraphQL implementation
 (refer to: https://github.com/graphql-java/graphql-java).
+++
|[[locations]]`locations`|`Array of link:dataobjects.html#ErrorLocation[ErrorLocation]`|
+++
@return the location(s) where the error occurred (if applicable)
+++
|[[message]]`message`|`String`|
+++
@return the error message
+++
|===

[[QueryResult]]
== QueryResult

++++
 Immutable data object that holds the execution result of a GraphQL query.
 <p>
 If the query was successful the response is available as . Otherwise a list of
  provides more detail on the failure.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[data]]`data`|`Json object`|
+++
Gets the  response of a successful GraphQL query. If the query wasn't
 successful an empty json object is returned.
+++
|[[errors]]`errors`|`Array of link:dataobjects.html#QueryError[QueryError]`|
+++
Gets the errors that occurred on query execution, if the GraphQL query was not successful.
+++
|[[succeeded]]`succeeded`|`Boolean`|
+++
@return <code>true</code> when the query was successful, <code>false</code> otherwise
+++
|===

[[SchemaMetadata]]
== SchemaMetadata

++++
 Metadata that is required for creation of service proxies of .
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[clientProxy]]`clientProxy`|`Boolean`|
+++
Gets the flag that determines whether to use a client proxy at the schema consumer side.
+++
|[[serviceAddress]]`serviceAddress`|`String`|
+++
Gets the address of the service proxy to use for the schema definition.
+++
|===

